runtime: python311

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  FLASK_ENV: "production"
  # Use /tmp for SQLite in App Engine (writable directory)
  DATABASE_URL: "sqlite:////tmp/prod.db"
  # SECRET_KEY: "change-this-in-production"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2

handlers:
  - url: /.*
    script: auto
    secure: always
