runtime: python311

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  FLASK_ENV: "production"
  # Use /tmp as the Flask instance path (writable on App Engine)
  FLASK_INSTANCE_PATH: "/tmp/instance"

  # Cloud SQL configuration (MySQL)
  DB_USER: "todo_user"
  DB_NAME: "todo_db"
  INSTANCE_CONNECTION_NAME: "todo-flask-gcp:europe-west2:todo-mysql"

  # Remove DB_PASS and DB_PASS_SECRET_NAME from here
  # DB_PASS: "MyStrongTodoPd123!"
  # DB_PASS_SECRET_NAME: "todo-db-password"

# Add this new section to securely inject the secret
secret_env_variables:
  DB_PASS: "projects/426639005612/secrets/todo-db-password/versions/1" # Or /latest if you want the most recent version


automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2

beta_settings:
  # This tells App Engine which Cloud SQL instance to connect to via /cloudsql/...
  cloud_sql_instances: "todo-flask-gcp:europe-west2:todo-mysql"

handlers:
  - url: /.*
    script: auto
    secure: always
