runtime: python311

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  FLASK_ENV: "production"
  # Use /tmp as the Flask instance path (writable on App Engine)
  FLASK_INSTANCE_PATH: "/tmp/instance"

  # Cloud SQL configuration (MySQL)
  DB_USER: "todo_user"
  DB_NAME: "todo_mysql"
  INSTANCE_CONNECTION_NAME: "todo-flask-gcp:europe-west2:todo-mysql"

  # ⚠️ IMPORTANT:
  # For now, you can either:
  #  - Put the real password here temporarily (NOT recommended for public repo), or
  #  - Use a placeholder here and override DB_PASS in the App Engine console
  DB_PASS: "P96184986Rt@123"

  # Optional: override secret key in production
  # SECRET_KEY: "change-this-in-production"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2

beta_settings:
  # This tells App Engine which Cloud SQL instance to connect to via /cloudsql/...
  cloud_sql_instances: "todo-flask-gcp:europe-west2:todo-mysql"

handlers:
  - url: /.*
    script: auto
    secure: always
