steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Deploy to App Engine"
    args:
      - "app"
      - "deploy"
      - "app.yaml"
      - "--quiet"

timeout: "900s"

options:
  logging: CLOUD_LOGGING_ONLY

