# cloudbuild.yaml
# CI/CD pipeline:
# 1) Install dependencies
# 2) Run tests with pytest
# 3) Deploy to App Engine if tests pass

steps:
  - name: "python:3.11"
    id: "Install dependencies and run tests"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pip install -r requirements.txt
        pytest -q

  - name: "gcr.io/cloud-builders/gcloud"
    id: "Deploy to App Engine"
    args:
      - "app"
      - "deploy"
      - "app.yaml"
      - "--quiet"

timeout: "900s"

options:
  logging: CLOUD_LOGGING_ONLY


